---
name: Base

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    # at 03:33 on Friday
    - cron: "33 3 * * 5"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: read

jobs:
  build:
    if: github.repository_owner == 'searxng' || github.event_name == 'workflow_dispatch'
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: "false"

      - name: Setup podman
        env:
          PODMAN_VERSION: "v5.6.2"
        run: |
          # dpkg man-db trigger is very slow on GHA runners
          # https://github.com/actions/runner-images/issues/10977
          # https://github.com/actions/runner/issues/4030
          sudo rm -f /var/lib/man-db/auto-update

          sudo apt-get purge -y podman runc crun conmon

          curl -fsSLO "https://github.com/mgoltzsche/podman-static/releases/download/${{ env.PODMAN_VERSION }}/podman-linux-amd64.tar.gz"
          curl -fsSLO "https://github.com/mgoltzsche/podman-static/releases/download/${{ env.PODMAN_VERSION }}/podman-linux-amd64.tar.gz.asc"
          gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 0CCF102C4F95D89E583FF1D4F8B5AF50344BB503
          gpg --batch --verify "podman-linux-amd64.tar.gz.asc" "podman-linux-amd64.tar.gz"

          tar -xzf "podman-linux-amd64.tar.gz"
          sudo cp -rfv ./podman-linux-amd64/etc/. /etc/
          sudo cp -rfv ./podman-linux-amd64/usr/. /usr/

          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Setup mise-en-place
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1

      - name: Get date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >>$GITHUB_OUTPUT

      - name: Setup cache container
        uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0 # v5.0.0
        with:
          # yamllint disable-line rule:line-length
          key: "container-${{ steps.date.outputs.date }}-${{ hashFiles('./Dockerfile') }}"
          restore-keys: |
            "container-${{ steps.date.outputs.date }}-"
            "container-"
          path: "/var/tmp/buildah-cache-*/*"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build
        run: mise run build --push
